#!/bin/bash

if [ ! -e /etc/firewallo ] ; then
mkdir /etc/firewallo/
cp -rf firewallo/* /etc/firewallo
cp /etc/firewallo/bin/firewallo.iptables /etc/init.d/firewallo.iptables
cp /etc/firewallo/bin/firewallo.nft /etc/init.d/firewallo.nft
cp /etc/firewallo/bin/firewallo /usr/sbin/

chmod +x /etc/init.d/firewallo.*
chmod +x /usr/sbin/firewallo
chmod -R +x /etc/firewallo/filter
chmod -R +x /etc/firewallo/nat
chmod -R +x /etc/firewallo/mangle
chmod -R +x /etc/firewallo/route

else
	echo "firewallo esiste!"
fi
