#!/bin/bash

if [ ! -e /etc/firewallo ] ; then
mkdir /etc/firewallo/
cp -rf ./* /etc/firewallo
cp ../init.d/firewallo.iptables /etc/init.d/firewallo.iptables
cp ../init.d/firewallo.nft /etc/init.d/firewallo.nft
cp ../../usr/sbin/firewallo /usr/sbin/

chmod +x /etc/init.d/firewallo.*
chmod +x /usr/sbin/firewallo
chmod -R +x /etc/firewallo/filter
chmod -R +x /etc/firewallo/nat
chmod -R +x /etc/firewallo/mangle
chmod -R +x /etc/firewallo/route

else
	echo "Firewallo already Exist!"
fi